# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\autobuy.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(692, 754)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fb_group = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.fb_group.setObjectName("fb_group")
        self.fb_account = QtWidgets.QLineEdit(self.fb_group)
        self.fb_account.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.fb_account.setObjectName("fb_account")
        self.fb_password = QtWidgets.QLineEdit(self.fb_group)
        self.fb_password.setGeometry(QtCore.QRect(10, 60, 301, 31))
        self.fb_password.setObjectName("fb_password")
        self.verticalLayout.addWidget(self.fb_group)
        self.phone_group = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.phone_group.setObjectName("phone_group")
        self.phonenum = QtWidgets.QLineEdit(self.phone_group)
        self.phonenum.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.phonenum.setObjectName("phonenum")
        self.verticalLayout.addWidget(self.phone_group)
        self.email_group = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.email_group.setObjectName("email_group")
        self.email_text = QtWidgets.QLineEdit(self.email_group)
        self.email_text.setGeometry(QtCore.QRect(10, 40, 301, 31))
        self.email_text.setObjectName("email_text")
        self.verticalLayout.addWidget(self.email_group)
        self.web_group = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.web_group.setObjectName("web_group")
        self.shopweb = QtWidgets.QLineEdit(self.web_group)
        self.shopweb.setGeometry(QtCore.QRect(10, 40, 301, 31))
        self.shopweb.setObjectName("shopweb")
        self.verticalLayout.addWidget(self.web_group)
        self.size_group = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.size_group.setObjectName("size_group")
        self.size_xpath = QtWidgets.QLineEdit(self.size_group)
        self.size_xpath.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.size_xpath.setObjectName("size_xpath")
        self.size_count = QtWidgets.QSpinBox(self.size_group)
        self.size_count.setGeometry(QtCore.QRect(270, 40, 51, 31))
        self.size_count.setObjectName("size_count")
        self.verticalLayout.addWidget(self.size_group)
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(480, 470, 121, 41))
        self.start_btn.setObjectName("start_btn")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 550, 671, 192))
        self.textBrowser.setObjectName("textBrowser")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "搶購機器人"))
        self.fb_group.setTitle(_translate("mainWindow", "FB帳號密碼"))
        self.phone_group.setTitle(_translate("mainWindow", "手機"))
        self.email_group.setTitle(_translate("mainWindow", "Email"))
        self.web_group.setTitle(_translate("mainWindow", "搶購網址"))
        self.size_group.setTitle(_translate("mainWindow", "選擇尺寸、數量"))
        self.start_btn.setText(_translate("mainWindow", "開始"))